### ISSUE TITLE
Preprinted text is overwritten by node-fzf

### ISSUE THREAD

**Issue by ArturGudiev** [talmobi/node-fzf#6]
I often need to print some text choosing an option in `node-fzf`. But if there are a lot of lines there, `node-fzf` will hide some of them. 

Example: 
```
const arr = [];
        for(let i = 0 ; i < 40; i++ ) {
            console.log(i);
            if ( i < 10 ) {
                arr.push('s' + i);
            }

        }
    const nfzf = require( 'node-fzf' )
    const opts = {
        list: arr
    }
    const result = await nfzf( opts ) 
```

Here I print 40 lines of the text. And after that, I call `node-fzf` with 10 options. As a result, it shows only 30 lines of the preprinted text. 

![image](https://user-images.githubusercontent.com/4563342/106356909-ef954e00-6313-11eb-852d-18931d77dc33.png)

**Comment by talmobi** [comment]
Yes. Depending on the available height of the terminal node-fzf will make room for itself at the bottom of the current cursor position in the terminal.

If this is just looks bad, you can clear the terminal before you call node-fzf.

If you need to show some printed text, clear the terminal, print a few lines, and then call node-fzf -- but if the available terminal height is small then the printed text will still be overwritten from the bottom up to make room for the selection options.

The third option, is for node-fzf to open a completely separate terminal screen to handle the selection. This is how, for example, the original `fzf` (made by junegunn) (link: https://github.com/junegunn/fzf). This third option is currently not supported by node-fzf, but it's possible to do (most likely most easiest to do with https://github.com/chjj/blessed).

Can you clarify how this is impacting your use-case (any of the above listed situations?) and how you would like it to behave?

**Comment by ArturGudiev** [comment]
@talmobi the first two cases don't suit me. I often need to print some text with a lot of lines. And it should stay on the screen because depending on it the user will choose the next option. Since this is not yet supported in the node-fzf, I should probably try the third case.

**Comment by talmobi** [comment]
You could just remember what you have printed, and re-print it after node-fzf finishes?

**Comment by ArturGudiev** [comment]
Unfortunately, I have dynamic content. And it's difficult to remember.

**Comment by ArturGudiev** [comment]
@talmobi probably you are right! I guess I will print the whole text and I will wait for the user to press enter. It's a decent workaround.

**Comment by talmobi** [comment]
I think even with dynamic content you should be able to store in some variable what you have printed previously.

**Comment by talmobi** [comment]
I miss-clicked close instead of cancel reply.

**Comment by ArturGudiev** [comment]
I think I can close it. 
But still.. if you allow printing a lot of lines without overwriting it by node-fzf list of options, it will be great!

**Comment by talmobi** [comment]
That was initially the idea. But since you can't read the terminal history before the program launches it can't be redrawn automatically.

Could possibly add some helper fn's to track this, though, to give the user more precise control over what has been overwritten in the terminal.

That or then do what `fzf` does and open up a new tty screen altogether.
