### ISSUE TITLE
Is there a way to format the output and/or only search over part of each line?

### ISSUE THREAD

**Issue by NullVoxPopuli** [talmobi/node-fzf#9]
For example, I'm making a repo search thing for navigating my local file system, and I have a lot of entries like:

```
NullVoxPopuli/project-a
NullVoxPopuli/project-b
NullVoxPopuli/project-c
tmp/project-d
```
and I'd like to be able to ignore everything left of the first `/` -- is that possible?

**Comment by talmobi** [comment]
You mean like `cat sample-input.txt | cut -d'/' -f2- | nfzf`?

**Comment by NullVoxPopuli** [comment]
oh, I forgot to mention I'm using the JS api. My current approach is to split the string, and then just move the folder to the end and see if using chalk for coloring works

**Comment by talmobi** [comment]
Oh, then you can do anything. Just plain JavaScript. You can input and output anything you want.

**Comment by NullVoxPopuli** [comment]
only sort of. `nfzf` takes a list, and each entry of the entire list is search over, as far as I understand it. does `nfzf` provide hooks to omit substrings of each entry in `list`?

**Comment by talmobi** [comment]
Just give `nfzf` as input the list you want with any of the substitutions you want to make to it. You can use the index in the nfzf return value to reference the exact same index in the origin list if you need to reference the non-filtered version of the value that you gave nfzf for displaying.

**Comment by NullVoxPopuli** [comment]
🤔 I didn't see any apis on the README that hint at being able to print a different list from what is searched over. How would you update the list as fzf narrows your resultts?

**Comment by talmobi** [comment]
I'm not sure I understand. Something like this?

```js
const nfzf = require('node-fzf')

const originalList = [
  'NullVoxPopuli/project-a',
  'NullVoxPopuli/project-b',
  'NullVoxPopuli/project-c',
  'tmp/project-d',
]

const filteredList = originalList.map(function (v) {
  return v.split('/').slice(1).join('/')
})

;(async function () {
  const opts = {
    list: filteredList
  }
  const r = await nfzf(opts)

  if ( r.selected ) {
    console.log(originalList[ r.selected.index ])
  } else {
    console.log('nothing selected')
  }
})()
```

for you can `opts.update( list )` with a new list?'

Should be in the README API section. But maybe I don't understand what you're trying to do?

**Comment by NullVoxPopuli** [comment]
> But maybe I don't understand what you're trying to do?

not quite -- maybe I'm not explaining myself well.

I don't want to prefilter or pre-trim the list. I only want to change what is searched over, but still display all the information, like:
![image](https://user-images.githubusercontent.com/199018/120082339-6529e480-c090-11eb-937f-dd79309d7464.png)

(Imagine the gray part isn't searched over)
but right now, any string that matches the gray text is selected:
![image](https://user-images.githubusercontent.com/199018/120082350-7a067800-c090-11eb-988c-e283287be36b.png)
which, for my purposes, isn't meaningful. 
So, I guess in summary:
 1. I want to display any text
 2. I want to specify what part of the text is allowed to match the input text

**Comment by NullVoxPopuli** [comment]
when I use normal fzf, I see this behavior: 
![image](https://user-images.githubusercontent.com/199018/120082460-3eb87900-c091-11eb-806e-75cc3696d3d8.png)
![image](https://user-images.githubusercontent.com/199018/120082465-4710b400-c091-11eb-9478-c78ce7e08b10.png)

which isn't perfect, but _is_ more inline with what I want

**Comment by talmobi** [comment]
Aha, I see. Indeed that is not possible.

Would something like `render-before-line` and `render-after-line` hooks work?

**Comment by NullVoxPopuli** [comment]
not sure -- what would those do?

**Comment by talmobi** [comment]
Allow you to control exactly what is printer before and after each line in the displayed list.

**Comment by NullVoxPopuli** [comment]
I think even if I could have a starting input of `/` that would help a lot

**Comment by NullVoxPopuli** [comment]
> Allow you to control exactly what is printer before and after each line in the displayed list.

sounds like it could work, as long as I can pass a list of objects, rather than a list of strings, so I can disambiguate between files/folders with the same name, but different root directories

**Comment by talmobi** [comment]
Hey, you can try v0.10.0?

Something like this:

```js
const nfzf = require('node-fzf')

const originalList = [
  'NullVoxPopuli/project-a',
  'NullVoxPopuli/project-b',
  'NullVoxPopuli/project-c',
  'tmp/project-d',
]

const filteredList = originalList.map(function (v) {
  return v.split('/').slice(1).join('/')
})

;(async function () {
  const opts = {
    list: filteredList,
    prelinehook: function ( i ) {
      const clc = nfzf.cliColor
      const clcFgGray = clc.xterm( 236 )

      const pre = originalList[ i ].split('/').shift()
      return clcFgGray( pre + '/' )
    },
    postlinehook: function ( i ) {
      const clc = nfzf.cliColor
      const clcFgGray = clc.xterm( 236 )

      const post = originalList[ i ].slice( -1 )
      return clcFgGray( '   | ' + clcFgGray( post ) )
    },
  }
  const r = await nfzf(opts)

  if ( r.selected ) {
    console.log(originalList[ r.selected.index ])
  } else {
    console.log('nothing selected')
  }
})()
```

**Comment by talmobi** [comment]
you get the original index value of the displayed line the hook functions -- so you should be able to grab whatever you need based on it.

**Comment by talmobi** [comment]
It could look and function something like this


![](https://i.imgur.com/I8XCora.gif)

**Comment by NullVoxPopuli** [comment]
oh that's nice!!!

**Comment by NullVoxPopuli** [comment]
what happen when `NullVoxPopuli` and  `tmp` has the same suffix / folder?

**Comment by NullVoxPopuli** [comment]
oh, I use the index. gonna try this

**Comment by NullVoxPopuli** [comment]
this works, gonna close. thanks for implementing!
